"""Detection Scenario Platform (DSP) — Phase 1A Core + Phase 1B DNS Foundation."""

__version__ = "1.2.0"
EVENT_SCHEMA_VERSION = "1.0.0"
VALIDATION_RESULT_SCHEMA = "1.0.0"
REPORT_FORMAT_VERSION = "1.0.0"
SCENARIO_INTERFACE_VERSION = "1.0.0"
MANIFEST_SCHEMA_VERSION = "1.0.0"
PROTOCOL_LIBRARY_VERSION = "1.0.0"
