#!/usr/bin/env bash
# DSP operator menu — update, configure, and run without memorizing CLI flags.
set -uo pipefail

SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
DEFAULT_REPO_DIR="$(cd "${SCRIPT_DIR}/.." && pwd)"

CONFIG_DIR="${HOME}/.dsp"
CONFIG_FILE="${CONFIG_DIR}/config.env"
RUNS_DIR="${HOME}/.dsp/runs"
RELEASE_BRANCH="release/v1.4.0-rc"

# shellcheck disable=SC2034
MENU_ITEMS=(
  "1:Update latest patch"
  "2:Configure environment"
  "3:Run scenario"
  "4:Show latest report"
  "5:Show version/status"
  "6:Exit"
)

has_whiptail() {
  command -v whiptail >/dev/null 2>&1
}

msg() {
  local text="$1"
  if has_whiptail; then
    whiptail --title "DSP Menu" --msgbox "$text" 12 72 2>/dev/null || true
  else
    printf '%s\n' "$text"
    read -r -p "Press Enter to continue..."
  fi
}

err() {
  local text="$1"
  if has_whiptail; then
    whiptail --title "DSP Menu — Error" --msgbox "$text" 12 72 2>/dev/null || true
  else
    printf 'ERROR: %s\n' "$text" >&2
    read -r -p "Press Enter to continue..."
  fi
}

ensure_config_dir() {
  mkdir -p "$CONFIG_DIR"
}

write_default_config() {
  ensure_config_dir
  cat >"$CONFIG_FILE" <<EOF
# DSP operator menu configuration (generated by dsp-menu.sh)
DSP_REPO_DIR=${DEFAULT_REPO_DIR}
TARGET_NET=10.10.10.0/24
EXECUTION_MODE=local
PROFILE=normal
WEBSHELL_FAMILY=jsp
WEBSHELL_URL=http://10.10.10.50:8080/shell.jsp
REMOTE_WORK_DIR=/tmp/dsp
EOF
}

load_config() {
  DSP_REPO_DIR="$DEFAULT_REPO_DIR"
  TARGET_NET="10.10.10.0/24"
  EXECUTION_MODE="local"
  PROFILE="normal"
  WEBSHELL_FAMILY="jsp"
  WEBSHELL_URL="http://10.10.10.50:8080/shell.jsp"
  REMOTE_WORK_DIR="/tmp/dsp"

  if [[ ! -f "$CONFIG_FILE" ]]; then
    write_default_config
  fi

  # shellcheck disable=SC1090
  source "$CONFIG_FILE"

  if [[ ! -d "$DSP_REPO_DIR" ]]; then
    DSP_REPO_DIR="$DEFAULT_REPO_DIR"
  fi
}

save_config() {
  ensure_config_dir
  cat >"$CONFIG_FILE" <<EOF
# DSP operator menu configuration (generated by dsp-menu.sh)
DSP_REPO_DIR=${DSP_REPO_DIR}
TARGET_NET=${TARGET_NET}
EXECUTION_MODE=${EXECUTION_MODE}
PROFILE=${PROFILE}
WEBSHELL_FAMILY=${WEBSHELL_FAMILY}
WEBSHELL_URL=${WEBSHELL_URL}
REMOTE_WORK_DIR=${REMOTE_WORK_DIR}
EOF
}

activate_dsp_env() {
  if [[ -f "${DSP_REPO_DIR}/.venv/bin/activate" ]]; then
    # shellcheck disable=SC1091
    source "${DSP_REPO_DIR}/.venv/bin/activate"
  fi
  export PATH="${DSP_REPO_DIR}/.venv/bin:${PATH}"
}

show_menu_whiptail() {
  whiptail --title "DSP Menu" --menu "Detection Scenario Platform" 18 72 10 \
    "1" "Update latest patch" \
    "2" "Configure environment" \
    "3" "Run scenario" \
    "4" "Show latest report" \
    "5" "Show version/status" \
    "6" "Exit" \
    3>&1 1>&2 2>&3
}

show_menu_plain() {
  printf '\n=== DSP Menu ===\n'
  printf '1) Update latest patch\n'
  printf '2) Configure environment\n'
  printf '3) Run scenario\n'
  printf '4) Show latest report\n'
  printf '5) Show version/status\n'
  printf '6) Exit\n'
  printf 'Choice [1-6]: '
  read -r choice
  printf '%s' "$choice"
}

pick_choice() {
  if has_whiptail; then
    show_menu_whiptail || return 1
  else
    show_menu_plain
  fi
}

do_update() {
  load_config
  local log
  log="$(mktemp)"
  {
    printf 'Repository: %s\n' "$DSP_REPO_DIR"
    printf 'Branch: %s\n\n' "$RELEASE_BRANCH"
    if [[ ! -d "${DSP_REPO_DIR}/.git" ]]; then
      printf 'ERROR: %s is not a git repository.\n' "$DSP_REPO_DIR"
      exit 1
    fi
    cd "$DSP_REPO_DIR"
    git fetch origin
    git checkout "$RELEASE_BRANCH"
    git pull origin "$RELEASE_BRANCH"
    printf '\nUpdate complete.\n'
    git log -1 --oneline
  } >"$log" 2>&1 || true

  if has_whiptail; then
    whiptail --title "Update latest patch" --scrolltext --textbox "$log" 20 72 2>/dev/null || true
  else
    cat "$log"
    read -r -p "Press Enter to continue..."
  fi
  rm -f "$log"
}

configure_whiptail() {
  local value

  value="$(whiptail --title "Configure" --inputbox "Target network (CIDR)" 10 72 "$TARGET_NET" 3>&1 1>&2 2>&3)" || return 1
  TARGET_NET="$value"

  value="$(whiptail --title "Configure" --radiolist "Execution mode" 14 72 2 \
    "local" "Run from this host" "$([[ "$EXECUTION_MODE" == "local" ]] && echo ON || echo OFF)" \
    "webshell" "Run via webshell provider" "$([[ "$EXECUTION_MODE" == "webshell" ]] && echo ON || echo OFF)" \
    3>&1 1>&2 2>&3)" || return 1
  EXECUTION_MODE="$value"

  value="$(whiptail --title "Configure" --radiolist "Traffic profile" 14 72 3 \
    "low" "Conservative volume" "$([[ "$PROFILE" == "low" ]] && echo ON || echo OFF)" \
    "normal" "Default operational profile" "$([[ "$PROFILE" == "normal" ]] && echo ON || echo OFF)" \
    "high" "High volume" "$([[ "$PROFILE" == "high" ]] && echo ON || echo OFF)" \
    3>&1 1>&2 2>&3)" || return 1
  PROFILE="$value"

  if [[ "$EXECUTION_MODE" == "webshell" ]]; then
    value="$(whiptail --title "Configure" --inputbox "Webshell family" 10 72 "$WEBSHELL_FAMILY" 3>&1 1>&2 2>&3)" || return 1
    WEBSHELL_FAMILY="$value"

    value="$(whiptail --title "Configure" --inputbox "Webshell URL" 10 72 "$WEBSHELL_URL" 3>&1 1>&2 2>&3)" || return 1
    WEBSHELL_URL="$value"

    value="$(whiptail --title "Configure" --inputbox "Remote work directory" 10 72 "$REMOTE_WORK_DIR" 3>&1 1>&2 2>&3)" || return 1
    REMOTE_WORK_DIR="$value"
  fi

  value="$(whiptail --title "Configure" --inputbox "DSP repository directory" 10 72 "$DSP_REPO_DIR" 3>&1 1>&2 2>&3)" || return 1
  DSP_REPO_DIR="$value"

  save_config
  msg "Configuration saved to ${CONFIG_FILE}"
}

configure_plain() {
  local value

  read -r -p "Target network [${TARGET_NET}]: " value
  [[ -n "$value" ]] && TARGET_NET="$value"

  printf 'Execution mode (local/webshell) [%s]: ' "$EXECUTION_MODE"
  read -r value
  [[ -n "$value" ]] && EXECUTION_MODE="$value"

  printf 'Profile (low/normal/high) [%s]: ' "$PROFILE"
  read -r value
  [[ -n "$value" ]] && PROFILE="$value"

  if [[ "$EXECUTION_MODE" == "webshell" ]]; then
    printf 'Webshell family [%s]: ' "$WEBSHELL_FAMILY"
    read -r value
    [[ -n "$value" ]] && WEBSHELL_FAMILY="$value"

    printf 'Webshell URL [%s]: ' "$WEBSHELL_URL"
    read -r value
    [[ -n "$value" ]] && WEBSHELL_URL="$value"

    printf 'Remote work dir [%s]: ' "$REMOTE_WORK_DIR"
    read -r value
    [[ -n "$value" ]] && REMOTE_WORK_DIR="$value"
  fi

  printf 'DSP repo dir [%s]: ' "$DSP_REPO_DIR"
  read -r value
  [[ -n "$value" ]] && DSP_REPO_DIR="$value"

  save_config
  msg "Configuration saved to ${CONFIG_FILE}"
}

do_configure() {
  load_config
  if has_whiptail; then
    configure_whiptail || true
  else
    configure_plain
  fi
}

do_run() {
  load_config
  activate_dsp_env

  if ! command -v dsp >/dev/null 2>&1; then
    err "dsp command not found. Install with: cd ${DSP_REPO_DIR} && python3 -m venv .venv && .venv/bin/pip install -e ."
    return
  fi

  local log
  log="$(mktemp)"
  {
    printf 'Profile: %s\n' "$PROFILE"
    printf 'Target net: %s\n' "$TARGET_NET"
    printf 'Execution mode: %s\n\n' "$EXECUTION_MODE"

    cd "$DSP_REPO_DIR"
    if [[ "$EXECUTION_MODE" == "webshell" ]]; then
      dsp run \
        --profile "$PROFILE" \
        --execution-provider webshell \
        --webshell-family "$WEBSHELL_FAMILY" \
        --webshell-url "$WEBSHELL_URL" \
        --remote-work-dir "$REMOTE_WORK_DIR" \
        --target-net "$TARGET_NET"
    else
      dsp run --profile "$PROFILE" --target-net "$TARGET_NET"
    fi
  } >"$log" 2>&1
  local rc=$?

  if has_whiptail; then
    whiptail --title "Run scenario (exit ${rc})" --scrolltext --textbox "$log" 22 78 2>/dev/null || true
  else
    cat "$log"
    read -r -p "Press Enter to continue..."
  fi
  rm -f "$log"
}

format_json_file() {
  local file="$1"
  if command -v python3 >/dev/null 2>&1; then
    python3 -m json.tool "$file" 2>/dev/null || cat "$file"
  else
    cat "$file"
  fi
}

do_show_report() {
  load_config
  local latest log
  log="$(mktemp)"

  if [[ ! -d "$RUNS_DIR" ]]; then
    printf 'No runs directory: %s\n' "$RUNS_DIR" >"$log"
  else
    latest="$(ls -td "${RUNS_DIR}"/* 2>/dev/null | head -1 || true)"
    if [[ -z "$latest" ]]; then
      printf 'No run directories under %s\n' "$RUNS_DIR" >"$log"
    else
      {
        printf 'Run directory:\n  %s\n\n' "$latest"
        if [[ -f "${latest}/traffic_summary.json" ]]; then
          printf '--- traffic_summary.json ---\n'
          format_json_file "${latest}/traffic_summary.json"
          printf '\n'
        else
          printf 'traffic_summary.json: (not found)\n\n'
        fi
        if [[ -f "${latest}/report.md" ]]; then
          printf 'report.md:\n  %s\n' "${latest}/report.md"
        else
          printf 'report.md: (not found)\n'
        fi
        if [[ -f "${latest}/verification_checklist.md" ]]; then
          printf 'verification_checklist.md:\n  %s\n' "${latest}/verification_checklist.md"
        else
          printf 'verification_checklist.md: (not found)\n'
        fi
      } >"$log"
    fi
  fi

  if has_whiptail; then
    whiptail --title "Latest report" --scrolltext --textbox "$log" 22 78 2>/dev/null || true
  else
    cat "$log"
    read -r -p "Press Enter to continue..."
  fi
  rm -f "$log"
}

do_show_status() {
  load_config
  activate_dsp_env

  local log
  log="$(mktemp)"
  {
    printf '=== Git ===\n'
    if [[ -d "${DSP_REPO_DIR}/.git" ]]; then
      cd "$DSP_REPO_DIR"
      printf 'Repo: %s\n' "$DSP_REPO_DIR"
      git branch --show-current 2>/dev/null || git rev-parse --abbrev-ref HEAD
      git log -1 --oneline 2>/dev/null || true
      printf '\nStatus:\n'
      git status -sb 2>/dev/null || true
    else
      printf 'Not a git repo: %s\n' "$DSP_REPO_DIR"
    fi

    printf '\n=== DSP ===\n'
    if command -v dsp >/dev/null 2>&1; then
      dsp --version 2>/dev/null || dsp --help 2>&1 | head -5
    else
      printf 'dsp command not found on PATH\n'
    fi

    printf '\n=== Config (%s) ===\n' "$CONFIG_FILE"
    if [[ -f "$CONFIG_FILE" ]]; then
      cat "$CONFIG_FILE"
    else
      printf '(missing)\n'
    fi
  } >"$log" 2>&1

  if has_whiptail; then
    whiptail --title "Version / status" --scrolltext --textbox "$log" 22 78 2>/dev/null || true
  else
    cat "$log"
    read -r -p "Press Enter to continue..."
  fi
  rm -f "$log"
}

main() {
  ensure_config_dir
  while true; do
    choice="$(pick_choice || true)"
    case "${choice:-}" in
      1) do_update ;;
      2) do_configure ;;
      3) do_run ;;
      4) do_show_report ;;
      5) do_show_status ;;
      6) exit 0 ;;
      "")
        ;;
      *)
        err "Invalid choice: ${choice}"
        ;;
    esac
  done
}

main "$@"
