"""DNS protocol library — Phase 1B foundation."""

from dsp.protocols.dns.client import DnsClient, build_query, encode_qname, parse_response, send_udp_query
from dsp.protocols.dns.events import (
    DNS_ERROR,
    DNS_QUERY_CREATED,
    DNS_QUERY_SENT,
    DNS_RESPONSE_RECEIVED,
    DNS_TIMEOUT,
    DNS_TRAFFIC_EVENTS,
    build_dns_events,
    map_outcome_to_event,
)
from dsp.protocols.dns.dga import (
    EFFECTIVE_TLD_DEFAULT,
    PHASE1_COUNT_DEFAULT,
    PHASE2_COUNT_DEFAULT,
    generate_nxdomain_fqdn,
    generate_resolvable_fqdn,
    is_nxdomain_fqdn,
    is_resolvable_fqdn,
    random_label,
)
from dsp.protocols.dns.dga_events import (
    DGA_COMPLETED,
    DGA_DOMAIN_GENERATED,
    DGA_NXDOMAIN_OBSERVED,
    DGA_RESOLVED_OBSERVED,
    DGA_STARTED,
    DGA_TRAFFIC_EVENTS,
    build_dga_completed_event,
    build_dga_domain_generated_event,
    build_dga_nxdomain_observed_event,
    build_dga_resolved_observed_event,
    build_dga_started_event,
)
from dsp.protocols.dns.dga_reporting import build_dga_report_section, dga_report_profile
from dsp.protocols.dns.dga_validation import DGA_METRIC_NAMES, dga_validation_profile
from dsp.protocols.dns.reporting import build_dns_report_section, dns_report_profile
from dsp.protocols.dns.tunnel import (
    CHUNK_SIZE_DEFAULT,
    PAYLOAD_MB_DEFAULT,
    TUNNEL_DOMAIN_DEFAULT,
    build_tunnel_fqdn,
    chunk_to_b32_label,
    is_valid_tunnel_fqdn,
    iter_payload_chunks,
    plan_chunk_count,
)
from dsp.protocols.dns.tunnel_events import (
    DNS_TUNNEL_CHUNK_CREATED,
    DNS_TUNNEL_COMPLETED,
    DNS_TUNNEL_QUERY_SENT,
    DNS_TUNNEL_STARTED,
    DNS_TUNNEL_TRAFFIC_EVENTS,
    build_tunnel_chunk_created_event,
    build_tunnel_completed_event,
    build_tunnel_query_sent_event,
    build_tunnel_started_event,
)
from dsp.protocols.dns.tunnel_reporting import build_dns_tunnel_report_section, dns_tunnel_report_profile
from dsp.protocols.dns.tunnel_validation import DNS_TUNNEL_METRIC_NAMES, dns_tunnel_validation_profile
from dsp.protocols.dns.validation import DNS_METRIC_NAMES, dns_validation_profile

__all__ = [
    "CHUNK_SIZE_DEFAULT",
    "DGA_COMPLETED",
    "DGA_DOMAIN_GENERATED",
    "DGA_METRIC_NAMES",
    "DGA_NXDOMAIN_OBSERVED",
    "DGA_RESOLVED_OBSERVED",
    "DGA_STARTED",
    "DGA_TRAFFIC_EVENTS",
    "DNS_ERROR",
    "EFFECTIVE_TLD_DEFAULT",
    "PHASE1_COUNT_DEFAULT",
    "PHASE2_COUNT_DEFAULT",
    "DNS_METRIC_NAMES",
    "DNS_TUNNEL_CHUNK_CREATED",
    "DNS_TUNNEL_COMPLETED",
    "DNS_TUNNEL_METRIC_NAMES",
    "DNS_TUNNEL_QUERY_SENT",
    "DNS_TUNNEL_STARTED",
    "DNS_TUNNEL_TRAFFIC_EVENTS",
    "DNS_QUERY_CREATED",
    "DNS_QUERY_SENT",
    "DNS_RESPONSE_RECEIVED",
    "DNS_TIMEOUT",
    "DNS_TRAFFIC_EVENTS",
    "DnsClient",
    "PAYLOAD_MB_DEFAULT",
    "TUNNEL_DOMAIN_DEFAULT",
    "build_dga_completed_event",
    "build_dga_domain_generated_event",
    "build_dga_nxdomain_observed_event",
    "build_dga_report_section",
    "build_dga_resolved_observed_event",
    "build_dga_started_event",
    "build_dns_events",
    "build_dns_report_section",
    "build_dns_tunnel_report_section",
    "build_query",
    "build_tunnel_chunk_created_event",
    "build_tunnel_completed_event",
    "build_tunnel_fqdn",
    "build_tunnel_query_sent_event",
    "build_tunnel_started_event",
    "chunk_to_b32_label",
    "dga_report_profile",
    "dga_validation_profile",
    "dns_report_profile",
    "dns_tunnel_report_profile",
    "generate_nxdomain_fqdn",
    "generate_resolvable_fqdn",
    "dns_tunnel_validation_profile",
    "dns_validation_profile",
    "encode_qname",
    "is_nxdomain_fqdn",
    "is_resolvable_fqdn",
    "is_valid_tunnel_fqdn",
    "random_label",
    "iter_payload_chunks",
    "map_outcome_to_event",
    "parse_response",
    "plan_chunk_count",
    "send_udp_query",
]
